# Generated by Django 4.2.4 on 2023-09-05 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vechile', '0003_alter_vechile_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_borrow', models.DateField(auto_now_add=True)),
                ('date_of_return', models.DateField()),
                ('fine', models.IntegerField(default=0)),
                ('returned', models.BooleanField(default=False)),
                ('proof', models.ImageField(upload_to='proof_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vechile.vechile')),
            ],
        ),
    ]
