# Generated by Django 4.2.4 on 2023-09-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vechile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('rent_per_day', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('vechile_image', models.ImageField(upload_to='vechile_pics')),
            ],
        ),
    ]
